services:
  db:
    image: postgres:latest
    container_name: project2_postgres
    env_file:
      - .db.env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
